language: python
dist: xenial
os: linux
python:
- '3.7'
install: pip install -r requirements.txt
script: py.test
deploy:
  provider: pypi
  username: mfreeborn
  password:
    secure: iJtnQ7I9HLs3MbHIfCOzScn2xPxJzpYSBSJC7PKt/a1FQ1ygLJ4ha7/031OTyKOYblpHvaUuXHnn1Q04AifivPTQHIS/ttqtqWiDTu5/ETnN3gjlQhrqVW4wbo81yDLcjkZF8wuai0XlMxLHhV+7VKuoKmuyg2IEcJX6GGLz07bG+cdKhwRaGAlfoaPGh+DxquYMCooHR3UqulQM3MH0t/aopfIsWdxnVm7A1Yh6QAmRg5cvShWxPGtUXVyluMUpH8vwLC1CdsjoNq4x2cf6aY/jEVhx1xrI1q1HBTw7PPMNDPvWXCQRCgPsoOCkFl3Lm+0dpoc5+hmT59HSi7/kFT4cXYMQ+4ahAdzEkXRb+x9Phf6w4fKjWJ/7Rmi78nLrqaHVCG+tJTf41xdn2FXmnu7w8Dj7k0urSvWjNaNCJFNdi6kLbrqFOPe4K+8vzHse4MVXaVXo+6KkHDvRtqZXiSWzS579oaHDiNXlYgCs0LV0Rp9xDXpbzKYYNbrW55lZ57yf9kEDje2GruvK9ZM+anVZEQkCQlpGtyyQM1nz0A9Qa1n0Wa00Ld42DNbnrIVNvyBfBI9vtMw6vD3EbOM/zJUjKzxRp4hp3ODaz660ZxbXC4KUiI/F9A3duZqkbM3n9HPoxgnG8WWco1OcswC77xNrZZbjALhN3XM2fAGt0fk=
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    tags: true
