language: python
dist: xenial
os: linux
python:
- '3.7'
install: pip install -r requirements.txt
script: py.test
deploy:
  provider: pypi
  username: mfreeborn
  password:
    secure: l8sKdFFlzFfvI/nPhD8ijf+VTt22bsB/PgzvkvQMfSz48my67viaP/NrCo9/xBqYxi+ThT4PsxZVdLKmdqw7zNezSz5xeICGvGqGPZ/O5bnkRY06ZgviSNBu3Lcu/EaSebqlkFzARX1YCBqXPr8PlfWijaTyz6a4zZaXFegi/imB67l8haid1WE1bSIlZfoo6o9b6Nca2Wftu5+RRUCXaN1eReGheyKewsT5kzyLF51ZT7+1SGXWVfVGdnDPL3fKbSp4qsfTrNM1+aZz0HHCOnAaefHkP2viaKxLAm384fT28XZqbr/4csJrS2m+lXcvG3kQxaFT735t80rFEd28A9D7/MnsxoffUFxlG6bH7bx3zyZnPHHCglGxYHcsidLCBsX4h5e1dKGDJpCNLe71ccBw3jKjWHn+n25Ej3RVKg4RkP08Y3jnRqCBuX71S/R8PHqv7IGW+sqc6Dl7UtfGc3EcJLfC+D18vPRSo4wvtrzSg5y+r6PP0gcgg6QuUaaCaz4/tBcZC/VQeUS3f4W6BJs7yvHqFP687YUTiwG6Ru2xw1+P5PWFCVAY5SOa8mGD5wUdv7xsLDVXqNCJab0BvmSdU0Q1UZJlZIaI7BqWoG5dStS+zM+eQbXRcPp2HJROXJM0badEkqFB7d1H2piyDJz+31w5vTyOxvYNNF0GCIU=
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    tags: true
